version: '3.8'

services:
  slspanel:
    image: alexanderwagnerdev/slspanel:beta
    container_name: slspanel
    restart: unless-stopped
    environment:
      - LANG=en
      - TZ=UTC
      - SLS_API_URL=http://sls-api-url:8789
      - SLS_API_KEY=yourapikey
      - SRT_PUBLISH_PORT=4000
      - SRT_PLAYER_PORT=4001
      - SRTLA_PUBLISH_PORT=5000
      - SLS_DOMAIN_IP=your-sls-domain-sls-domain-ip
      - SLS_STATS_PORT=8789
      - REQUIRE_LOGIN=True
      - USERNAME=admin
      - PASSWORD=password
    ports:
      - "8000:8000/tcp"
